version: '3.8'

services:
  api:
    container_name: acaiwaveplus-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "7475:7475" 
    restart: always
