version: '3.8'

services:
  api:
    container_name: acaiwaveplus-api
    build: .
    env_file:
      - .env
    volumes:
      - ./firebase-admin-sdk.json:/app/firebase-admin-sdk.json:ro
    ports:
      - "7475:7475"
    restart: always
