version: '3.8'

services:
  acaiwaveplus-backend:
    container_name: acaiwaveplus-backend
    build: .
    ports:
      - "7475:7475"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
