name: Deploy para VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Criar arquivo .env e JSON
        run: |
          echo "PORT=7475" >> .env
          echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> .env
          echo '${{ secrets.FIREBASE_ADMIN_SDK_JSON }}' > firebase-admin-sdk.json
          echo "FIREBASE_ADMIN_SDK=./firebase-admin-sdk.json" >> .env

      - name: Login na VPS via SSH e Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /caminho/do/projeto
            git pull origin main
            docker-compose --env-file .env up --build -d
